import Head from "next/head";
import React from "react";
import Header from "../organisms/Header";
import { CssBaseline } from "@mui/material";

const Layout = ({ children }: React.PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Watch Movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1 user-scalable=no; maximum-scale=1; minimum-scale=1;"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CssBaseline />
        <Header isMain={false} />
        {children}
      </main>
    </>
  );
};

export default Layout;
